#!/bin/bash
# Ensure vim is default editor

eval $(ssh-agent)
export EDITOR=vim

# custom alias for bash
alias hs='history | grep -i'
alias ls='ls -G'
alias genpasswd='openssl rand -base64'
alias sshls="grep Host ~/.ssh/config"
alias sshconfig="less ~/.ssh/config"
alias listallcli="ls /usr/bin | xargs whatis | grep -v nothing | less"
alias TodayWeather="curl wttr.in/$1"
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -la'
alias l='ls'
alias l.="ls -A | egrep '^\.'"
alias cpp11="g++ -Wall --std=c++11"
alias cpp14="g++ -Wall --std=c++14"
alias cpp17="g++ -Wall --std=c++17"

# Install vim Plug

InstallPlug(){
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

# Search commandlinefu.com from the command line using the API

cmdfu(){ 
  curl -L "http://www.commandlinefu.com/commands/matching/$@/$(echo -n $@ | openssl base64)/plaintext"; 

}

# list duplication of file with size and then checksum

find_duplication(){

  find -not -empty -type f -printf "%s\n" | sort -rn | uniq -d | xargs -I{} -n1 find -type f -size {}c -print0 | xargs -0 md5sum | sort | uniq -w32 --all-repeated=separate
}


