#!/bin/bash
# list of one-liners and other bash related alias
alias ll="ls -la"

# list duplication of file wuth size and then checksum
alias find_duplication="find -not -empty -type f -printf "%s\n" | sort -rn | uniq -d | xargs -I{} -n1 find -type f -size {}c -print0 | xargs -0 md5sum | sort | uniq -w32 --all-repeated=separate"
