#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill --randomize $HOME/Pictures/backgrounds/* &

# PolyBar settings
pkill polybar
sleep 1;
polybar mybar -c ~/.config/polybar/config.ini &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7

# Other stuff
bspc config border_width         5
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config top_padding          10

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Remove x cursor 
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color3"

